config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :comments, except: [:index]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent,  class_name: "Comment"
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true

  default_scope    { order(:created_at) }
  scope :roots, -> { where(parent_id: nil) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]

  def new
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  def create
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    @success = comment.save
  end

  def edit; end

  def update
    respond_to do |format|
      if @comment.update(content: params[:content])
        format.json { render json: { content: @comment.content } }
      else
        format.json { render json: { errors: @comment.errors.message }}
      end
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @comments = Comment.roots
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.slim
.comments-comment-container id="comment-#{comment.id}"
  .comment-conent
    .media
      .media-left
        = link_to image_tag('user_avatar.png', class: 'avatar'), '#', class: 'media-object'
      .media-body
        = link_to comment.user.email, '#', class: 'username'
        p.comment-body = comment.content
        ul
          li = link_to 'Reply', new_comment_path(parent_id: comment.id), remote: true
          - if comment.user == current_user
            li = link_to 'Edit', edit_comment_path(comment), remote: true
            li = link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Delete this comment. Sure?' }, remote: true
          li = link_to 'Like', '#'
          li = comment.created_at.strftime('%A, %b %d')
  .comment-replies id="replies-of-comment-#{comment.id}"
    = render comment.replies if comment.replies.any?

app/views/comments/_form.html.slim
.comments-form-container
  = simple_form_for comment, defaults: {label: false}, remote: true do |f|
    = f.input :parent_id, as: :hidden, value: comment.parent_id
    = f.input :content
    = f.submit 'Add Comment'

app/views/comments/_list.html.slim
.comments-list-container
  = render comments
  = render 'comments/form', comment: Comment.new
  

app/views/comments/create.js.erb
<% if @success %>
  $("#home-index-container").html("<%=j render 'comments/list', comments: Comment.roots %>");
<% else %>
  alert('Error when create comment');
<% end %>

app/views/comments/new.js.erb
$("#replies-of-comment-<%= @comment.parent_id %>").append("<%=j render 'comments/form', comment: @comment %>");

app/views/home/index.html.slim
#home-index-container
  = render 'comments/list', comments: @comments
  

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container
    .navbar-brand= link_to 'Nested Comments', root_path
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li= link_to 'Sign Out', destroy_user_session_path, method: :delete
      - else
        li= link_to 'Sign Up', new_user_registration_path
        li= link_to 'Sign In', new_user_session_path

app/views/layouts/_message.html.slim
- flash.each do |name, msg|
  = content_tag :div, msg, class: 'alert'
  

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Nested Comments
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .container
      = render 'layouts/message'
      = yield